"""
Speed Logサンプル記事を生成するスクリプト。
200-400語の速報記事をHTMLで出力する。
"""

import sys
if sys.stdout.encoding != "utf-8":
    sys.stdout.reconfigure(encoding="utf-8")

from nowpattern_article_builder import build_speed_log_html

html = build_speed_log_html(
    title="EU、Apple制裁金€1.84B — DMA初の大型執行",
    why_it_matters="DMA施行後最大の制裁金。全ゲートキーパー企業のビジネスモデルに波及する判例となる。",
    facts=[
        ("€1.84B", "DMA第5条違反としてAppleに制裁金を正式決定"),
        ("Apple", "即座に上訴を表明。「DMAの過度な拡大解釈」と声明"),
        ("開発者団体", "Coalition for App Fairnessが「歴史的勝利」と宣言"),
    ],
    dynamics_tag="プラットフォーム支配",
    dynamics_one_liner="App Store独占構造にEUが初めて法的な限界を設定した。30%手数料モデルの正当性が問われている。",
    base_scenario="Appleは上訴しつつEU域内で手数料を段階的に引き下げ（30%→22%）。2027年までに17-20%に落ち着く。",
    genre_tags="テクノロジー",
    event_tags="司法・制裁",
    source_url="https://ec.europa.eu/commission/presscorner/detail/en/ip_26_XXX",
    deep_pattern_url="https://nowpattern.com/eu-apple-fine-structure/",
)

full_html = f"""<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Speed Log Sample — Nowpattern</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700&display=swap');
    body {{
      font-family: 'Noto Sans JP', sans-serif;
      max-width: 780px;
      margin: 0 auto;
      padding: 40px 20px;
      color: #121e30;
      line-height: 1.8;
      background: #fafaf7;
    }}
    h1 {{ font-size: 1.5em; line-height: 1.3; margin-bottom: 24px; }}
    h2 {{ font-size: 1.3em; margin-top: 32px; }}
    .mode-badge {{
      display: inline-block;
      background: #c9a84c;
      color: #121e30;
      padding: 4px 12px;
      border-radius: 4px;
      font-size: 0.8em;
      font-weight: bold;
      letter-spacing: 0.1em;
      margin-bottom: 8px;
    }}
    .word-count {{
      font-size: 0.85em;
      color: #888;
      margin-top: 24px;
      padding: 8px;
      background: #f0f0f0;
      border-radius: 4px;
    }}
  </style>
</head>
<body>
  <div class="mode-badge">SPEED LOG</div>
  <h1>EU、Apple制裁金€1.84B — DMA初の大型執行</h1>
  {html}
  <div class="word-count">
    <strong>Article ID:</strong> sl-2026-0218-001<br>
    <strong>Mode:</strong> Speed Log<br>
    <strong>Target:</strong> 200-400語<br>
    <strong>Dynamics:</strong> プラットフォーム支配<br>
    <strong>Deep Pattern link:</strong> <a href="https://nowpattern.com/eu-apple-fine-structure/">詳細分析記事</a><br>
    <strong>Generated by:</strong> Nowpattern Article Builder v3.0
  </div>
</body>
</html>"""

output_path = "scripts/nowpattern_sample_speed_log.html"
with open(output_path, "w", encoding="utf-8") as f:
    f.write(full_html)

print(f"OK: Speed Log sample written to {output_path}")
print(f"HTML size: {len(full_html):,} chars")

import re
text_only = re.sub(r'<[^>]+>', '', html)
text_only = re.sub(r'\s+', ' ', text_only).strip()
char_count = len(text_only)
print(f"Text content: {char_count:,} characters (≈ {char_count * 2 // 3:,} 日本語語数)")
